/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AgencySlugImport } from './routes/agency.$slug'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AgencySlugRoute = AgencySlugImport.update({
  id: '/agency/$slug',
  path: '/agency/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/agency/$slug': {
      id: '/agency/$slug'
      path: '/agency/$slug'
      fullPath: '/agency/$slug'
      preLoaderRoute: typeof AgencySlugImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agency/$slug': typeof AgencySlugRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agency/$slug': typeof AgencySlugRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/agency/$slug': typeof AgencySlugRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agency/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agency/$slug'
  id: '__root__' | '/' | '/agency/$slug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgencySlugRoute: typeof AgencySlugRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgencySlugRoute: AgencySlugRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/agency/$slug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/agency/$slug": {
      "filePath": "agency.$slug.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
